### ISSUE TITLE
Shipping to switzerland

### ISSUE THREAD

**Issue by guymayor** [Toybox-Labs/support-page#1]
Hi,
I have made an order, with us shipping only. 
I would like to have an international shipping cost for switzerland.
Thanks

Guy Mayor

**Comment by andypavia** [comment]
Hi Guy,

It's really nice to hear from you again. Unfortunately, we are not shipping to Switzerland at the moment because we do not have the infrastructure or operational arm over there. We hope to have operations there towards the end of this year. For any shipping request, please email sales@make.toys.

Regards,

Andy
